### ISSUE TITLE
F***ING CRASHED MY GAME

### ISSUE THREAD

**Issue by Nardeem** [Rosalie241/SporeCrashFix#1]
IT CRASHED MY GAME RIGHT AFTER SAVING A CREATION I WORKED ON FOR SO LONG, THIS IS ACTUALLY THE WORST MOD EVER, WHAT WAS I THINKING?!

**Comment by Rosalie241** [comment]
If you actually took time to read the description of the mod, you'd see that it doesn't fix all crashes, just a few I've encountered myself.

Taking out your frustrations on me, someone who made this mod in their spare time for nothing in return, isn't a nice thing to do so I'll close the issue.
